# Net
net: 'models.qdgnn.Model'
resume: ''
padding_input: False
device_ids: [1]
in_channels: 4
rinv: True

# Data
dataset: 'fpha'
ntu: '../data/NTU-RGB-D/qrel/xview'
fpha: '../data/fpha/qrel'
use_edge: True
edge_only: False
data_augmentation: True 
# Since fitting ability of QDGNN is too strong, DA here can significantly reduce overfitting.
data_param:
  num_frames: 100

# Optimizer
num_epochs: 100
start_epoch: 1
batch_size: 32
learning_rate: 1e-3
weight_decay: 1e-5

# Log
logdir: '../logs/qdgnn_dAug_FPHA_qrel'
tqdm: True