# Net
net: 'models.mlp_lstm.QLSTM'
resume: ''
padding_input: False
device_ids: [0]
in_channels: 4
rinv: True

# Data
dataset: 'fpha'
ntu: '../data/NTU-RGB-D/qrel/xview'
fpha: '../data/fpha/qrel'
use_edge: False
edge_only: False
data_augmentation: False
data_param:
  num_frames: 100

# Optimizer
num_epochs: 200
start_epoch: 1
batch_size: 32
learning_rate: 5e-4
weight_decay: 1e-5

# Log
logdir: '../logs/qmlp'
tqdm: True